version: "3.7"
services:
  code:
    image: "ghcr.io/linuxserver/code-server:latest"
    container_name: code
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Seoul
      - PASSWORD=password
      - SUDO_PASSWORD=password
      - DISABLE_TELEMETRY=true
      # - DOCKER_MODS=linuxserver/mods:code-server-golang|linuxserver/mods:code-server-java11|linuxserver/mods:code-server-nodejs|linuxserver/mods:code-server-python3|linuxserver/mods:code-server-zsh # Option
    ports:
      - 8443:8443
    volumes:
      - ./code_data:/config
      # - ./custom-init/custom-cont-init.d:/config/custom-cont-init.d:ro # Option - Custom Init
      # - ./custom-init/custom-services.d:/config/custom-services.d:ro # Option - Custom Services
    restart: unless-stopped
