version: "3.7"
services:
  code:
    image: "ghcr.io/linuxserver/code-server:latest"
    container_name: code
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Seoul
      - PASSWORD=password
      - SUDO_PASSWORD=password
      - DISABLE_TELEMETRY=true
    ports:
      - 12345:12345
    volumes:
      - ./code_data:/config
      - ./custom-init/custom-cont-init.d:/config/custom-cont-init.d:ro
      - ./custom-init/custom-services.d:/config/custom-services.d:ro
    restart: unless-stopped
