#!/usr/bin/with-contenv bash

# amd64
DL_PATH_URL="$(wget --no-check-certificate -qO- https://golang.org/dl/ | grep -oP '\/dl\/go([0-9\.]+)\.linux-amd64\.tar\.gz' | head -n 1)" 
go_latest_ver="$(echo $DL_PATH_URL | grep -oP 'go[0-9\.]+' | grep -oP '[0-9\.]+' | head -c -2 )"
echo "go ver is $go_latest_ver"

if [ -d /usr/local/go ]; then
    echo "Golang already installed, skipping"
else
    echo "--go downloading...--"
    cd ~/
    wget --no-check-certificate --continue --show-progress https://golang.org/dl/go${go_latest_ver}.linux-amd64.tar.gz
    tar -xzf go${go_latest_ver}.linux-amd64.tar.gz
    sudo mv go /usr/local
    rm ~/go${go_latest_ver}.linux-amd64.tar.gz
    
    echo "Installing gcc, to make CGO work"
    apt-get install -y gcc
fi

echo "ensuring golang is in PATH"
if grep -q -E '^(export )?PATH=' /etc/services.d/code-server/run; then
    if ! grep -q -E '^(export )?PATH=.*/usr/local/go/bin.*' /etc/services.d/code-server/run; then
        sed -i '/PATH/ s/$/:\/usr\/local\/go\/bin/' /etc/services.d/code-server/run
    fi
    if ! grep -q -E '^(export )?PATH=.*/config/go/bin:.*' /etc/services.d/code-server/run; then
        sed -i 's/PATH=/PATH=\/config\/go\/bin:/g' /etc/services.d/code-server/run
    fi
else
    sed -i '/^#!\/usr\/bin/a \\n# Added by codeserver-golang\nexport PATH=/config/go/bin:$PATH:/usr/local/go/bin' /etc/services.d/code-server/run
fi
